### ISSUE TITLE
GPU Memory allocation error

### ISSUE THREAD

**Issue by chiranjibsur** [chiranjibsur/eLBM#1]
**Development Branch** : doric_opt1 (https://github.com/chiranjibsur/eLBM/tree/doris_opt1)

**Brief history or records shared via emails**:

------------------
Entry : 3 : @chiranjibsur _(Jan 16, 2019)_
------------------

Error log:
```
GPU Mem required:  0.3GB from Proc# 1
-----------------------------------------
GPU Mem required:  0.3GB from Proc# 3
-----------------------------------------
GPU Mem required:  0.3GB from Proc# 4
-----------------------------------------
GPU memory allocation failed (0)a
GPU Mem required:  0.3GB from Proc# 2
-----------------------------------------
GPU Mem required:  0.3GB from Proc# 6
-----------------------------------------
Initialisation of the host completed.

===============================================

===============================================
Details of the GPUs installed:

Device Count: 8
GPU Mem required:  0.3GB from Proc# 9
-----------------------------------------
GPU Mem required:  0.3GB from Proc# 5
-----------------------------------------
GPU memory allocation failed (0)a
GPU memory allocation failed (0)a
GPU memory allocation failed (0)a
GPU memory allocation failed (0)a
GPU memory allocation failed (0)a
GPU Mem required:  0.3GB from Proc# 13
-----------------------------------------
GPU Mem required:  0.3GB from Proc# 12
-----------------------------------------
GPU memory allocation failed (0)a
GPU memory allocation failed (0)a
GPU Mem required:  0.3GB from Proc# 14
-----------------------------------------
GPU Mem required:  0.3GB from Proc# 7
-----------------------------------------
GPU memory allocation failed (0)a
GPU memory allocation failed (0)a
GPU Mem required:  0.3GB from Proc# 11
-----------------------------------------
GPU Mem required:  0.3GB from Proc# 10
-----------------------------------------
GPU memory allocation failed (0)a
GPU memory allocation failed (0)a
Device properties:
Device name:       Tesla V100-PCIE-16GB
Total Global Mem:    15.8GB
Number of Streaming Multiprocessors:  80
Shared Mem Per SM:   48KB
Max Number of Threads per Block:  1024
Max Number of Blocks allowed in x-dir:  2147483647
Max Number of Blocks allowed in y-dir:  65535
Warp Size:  32
===============================================

GPU Mem required:  0.3GB from Proc# 8
-----------------------------------------
GPU memory allocation failed (0)a

```
------------------
Entry : 2 : @dorisnvidia _(Jan 14, 2019)_
------------------

Can you in around Line 2290, replace the printf block with the following lines? 

  ```
char processor_name[MPI_MAX_PROCESSOR_NAME];
  int name_len;
  MPI_Get_processor_name(processor_name,&name_len);
  int gpuDevice;
  SafeCudaCall(cudaGetDevice(&gpuDevice));
```

  ```
//Send node data to GPU                                                                                                                                
  printf("GPU Mem required:  %.1fGB from Proc# %i on node %s gpu# %i \n",
         ((double)(TotalMem_dbl + TotalMem_dbl_conc +TotalMem_sgl+TotalMem_sgl_map))/1073741824.0,
         myPE, processor_name, gpuDevice);
  printf("-----------------------------------------\n");
……
  cudaStatus = cudaMalloc((void**)&GPUDataAddr_dbl, TotalMem_dbl);
  if (cudaStatus != cudaSuccess) {
    fprintf(stderr, "GPU memory allocation failed (0)a at myPE %i\n", myPE);
    goto Error;
  }

```
Run the job, it would report something like:
```
GPU Mem required:  0.3GB from Proc# 2 on node hsw218 gpu# 2
GPU Mem required:  0.3GB from Proc# 12 on node hsw222 gpu# 0
GPU Mem required:  0.3GB from Proc# 4 on node hsw220 gpu# 0
GPU Mem required:  0.3GB from Proc# 11 on node hsw221 gpu# 3
GPU Mem required:  0.3GB from Proc# 1 on node hsw218 gpu# 1
GPU Mem required:  0.3GB from Proc# 13 on node hsw222 gpu# 1
```
…
Then you should see which node and which gpu the memory allocation error is from. 

Please , also do the same exercise after commenting out the line 380, i.e., the line right before MPI_Init
SetDeviceBeforeInit();

I have to add this line to associate each MPI rank within a node to a different GPU. Otherwise, the output would show the following, which is not what I want. 
```
GPU Mem required:  0.3GB from Proc# 2 on node hsw218 gpu# 0
GPU Mem required:  0.3GB from Proc# 14 on node hsw222 gpu# 0
GPU Mem required:  0.3GB from Proc# 13 on node hsw222 gpu# 0
GPU Mem required:  0.3GB from Proc# 1 on node hsw218 gpu# 0
GPU Mem required:  0.3GB from Proc# 3 on node hsw218 gpu# 0
```
…

But if your cluster is set up a different way, you may not need that line. Anyway, let me know what you see. 

------------------
Entry : 1 : @chiranjibsur _(Jan 14, 2019)_
------------------
 Memory allocation error observed in the v100 system
```

GPU Mem required:  0.3GB from Proc# 4
-----------------------------------------
GPU Mem required:  0.3GB from Proc# 5
-----------------------------------------
GPU Mem required:  0.3GB from Proc# 1
-----------------------------------------
GPU Mem required:  0.3GB from Proc# 9
-----------------------------------------
GPU memory allocation failed (0)a
GPU Mem required:  0.3GB from Proc# 13
-----------------------------------------
```

System information of v100 is the following: 

```
[incsu0@houcy1-n-cp338d03 V100-dorisRun]$ lspci | grep ' VGA ' | cut -d" " -f 1 | xargs -i lspci -v -s {}
03:00.0 VGA compatible controller: ASPEED Technology, Inc. ASPEED Graphics Family (rev 41) (prog-if 00 [VGA controller])
        Subsystem: ASPEED Technology, Inc. ASPEED Graphics Family
        Flags: bus master, medium devsel, latency 0, IRQ 17, NUMA node 0
        Memory at 9c000000 (32-bit, non-prefetchable) [size=16M]
        Memory at 9d000000 (32-bit, non-prefetchable) [size=128K]
        I/O ports at 2000 [size=128]
        Expansion ROM at <unassigned> [disabled]
        Capabilities: <access denied>
        Kernel driver in use: ast
        Kernel modules: ast

```

**Comment by dorisnvidia** [comment]
Chiranjib, 

Did you edit the prinf as I suggested? Looks like your output still show
...
GPU Mem required:  0.3GB from Proc# 1
GPU memory allocation failed (0)a
..
With the prinf edit, the output will show which node and which gpu is associated with each MPI rank, and if the GPU memory allocation error, it shows it occurs on which gpu. That would give us clue on what to do next. 

Doris

**Comment by chiranjibsur** [comment]
I tried with your latest branch (https://github.com/chiranjibsur/eLBM/tree/doris_opt3) and using the cuda aware OpenMPI libraries. However, still the program is crashing while doing the GPU memory allocation. Here is the complete log. Let's discuss this in tomorrow's meeting:

```
GPU memory allocation failed (0)a
GPU memory allocation failed (0)a
GPU memory allocation failed (0)a
GPU memory allocation failed (0)a
GPU memory allocation failed (0)a
GPU memory allocation failed (0)a
GPU memory allocation failed (0)a
GPU memory allocation failed (0)a
GPU memory allocation failed (0)a
GPU memory allocation failed (0)a
GPU memory allocation failed (0)a
GPU memory allocation failed (0)a
--------------------------------------------------------------------------
mpiexec has exited due to process rank 5 with PID 0 on
node houcy1-n-cp338a01 exiting improperly. There are three reasons this could occur:

1. this process did not call "init" before exiting, but others in
the job did. This can cause a job to hang indefinitely while it waits
for all processes to call "init". By rule, if one process calls "init",
then ALL processes must call "init" prior to termination.

2. this process called "init", but exited without calling "finalize".
By rule, all processes that call "init" MUST call "finalize" prior to
exiting or it will be considered an "abnormal termination"

3. this process called "MPI_Abort" or "orte_abort" and the mca parameter
orte_create_session_dirs is set to false. In this case, the run-time cannot
detect that the abort call was an abnormal termination. Hence, the only
error message you will receive is this one.

This may have caused other processes in the application to be
terminated by signals sent by mpiexec (as reported here).

You can avoid this message by specifying -quiet on the mpiexec command line.
```

**Comment by dorisnvidia** [comment]
Hi Chiranjib, 

As what discussed yesterday, I built openMPI 4.0.0 with cuda9.0 on our system. I am able to compile run eLBM code with my locally build OpenMPI and ran correctly. Here is the step I used to build openMPI:

tar -xvf openmpi-4.0.0.tar
cd openmpi-4.0.0
mkdir BLD

./configure --without-ucx --disable-silent-rules --enable-shared --enable-static --enable-mpi-fortran --enable-mpi-cxx --enable-mpi-cxx-seek --enable-cxx-exceptions --with-cuda=/cm/extra/apps/CUDA/9.0.176_384.81 --with-verbs=yes --enable-orterun-prefix-by-default --with-hwloc=/cm/extra/apps/HWLoc/1.11.8/GCC-6.4.0_CUDA-9.0.176 --with-zlib=/cm/extra/apps/ZLib/1.2.8/GCC-6.4.0 --with-slurm --prefix=/home/dorisp/TarBalls/openmpi-4.0.0/BLD

make -j8 install

====================
Then to compile eLBM, I have to load modules:
  1) gcc/6.4.0       2) cuda/9.0.176    3) slurm/16.05.0

to compile:
nvcc -std=c++11 --maxrregcount=128 -O3 --ptxas-options=-v -o bin/eLBM_v3_3 src/eLBM_v3_3.cu -L/home/dorisp/TarBalls/openmpi-4.0.0/BLD/lib -lmpi -I/home/dorisp/TarBalls/openmpi-4.0.0/BLD/include -gencode arch=compute_60,code=sm_60 -gencode arch=compute_70,code=sm_70  -DPARALLEL

to run:
/home/dorisp/TarBalls/openmpi-4.0.0/BLD/bin/mpiexec -np 4 -npernode 4  --mca btl_openib_cuda_async_recv false --mca btl_smcuda_use_cuda_ipc 0 ~/eLBM/bin/eLBM_v3_3
(as we build openmpi library as both static and shared, there is no need to set LD_LIBRARY_PATH at run time).

Results are good:
GPU Mem required:  1.2GB from Proc# 2 on node hsw212 gpu# 2
-----------------------------------------
GPU Mem required:  1.2GB from Proc# 1 on node hsw212 gpu# 1
-----------------------------------------
GPU Mem required:  2.0GB from Proc# 3 on node hsw212 gpu# 3
-----------------------------------------
GPU Mem required:  2.0GB from Proc# 0 on node hsw212 gpu# 0
....
After 2500 time-steps:

Wetting phase:
Average Velocity   = (7.81691e-06, -1.30280e-06, 1.98117e-06)
Velocity magnitude = 8.16862e-06 (+inf%)
Variance magnitude = 6.97830e-09 (+inf%)
Non-Wetting phase:
Average Velocity   = (9.99409e-06, -6.83924e-05, 1.38779e-05)
Velocity magnitude = 7.04983e-05 (-nan%)
Variance magnitude = 3.63921e-07 (-nan%)

Completed Step: 2500. Elapsed time since previous gathering point: 21.3 seconds

Please try to replicate my steps and see if it works for your on your cluster. 

Doris

**Comment by chiranjibsur** [comment]
This issue has been resolved. Closing this item.
